kafka:
  host: 172.16.1.141
  port: 9092
  cluster: false

datastore:
  host: 172.16.1.164
  port: 54321
  uid: postgres
  pwd: reporter
  db: store
  schema: public

app:
  key: eaeadmin
  debug: true
  host: 0.0.0.0
  port: 39099
  token: 366
